version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: delivery_db       
      POSTGRES_USER: pitoho         
      POSTGRES_PASSWORD: babymonster 
    volumes:
      - ./data:/var/lib/postgresql/data  
